# Generated by Django 3.0 on 2019-12-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnthemAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=255, unique=True)),
                ('asset_number', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AnthemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_four', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_userfour', to='leet.AnthemAsset')),
                ('asset_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_userone', to='leet.AnthemAsset')),
                ('asset_three', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_userthree', to='leet.AnthemAsset')),
                ('asset_two', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_usertwo', to='leet.AnthemAsset')),
            ],
        ),
    ]
