# Generated by Django 3.0 on 2019-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthemasset',
            name='asset_type',
            field=models.CharField(max_length=255),
        ),
    ]
