# Generated by Django 3.0 on 2019-12-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0003_auto_20191228_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthemuser',
            name='asset_four',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_userfour', to='leet.AnthemAsset'),
        ),
        migrations.AlterField(
            model_name='anthemuser',
            name='asset_three',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_userthree', to='leet.AnthemAsset'),
        ),
    ]
