# Generated by Django 3.0 on 2019-12-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0004_auto_20191228_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthemuser',
            name='asset_four',
        ),
        migrations.RemoveField(
            model_name='anthemuser',
            name='asset_one',
        ),
        migrations.RemoveField(
            model_name='anthemuser',
            name='asset_three',
        ),
        migrations.RemoveField(
            model_name='anthemuser',
            name='asset_two',
        ),
        migrations.AddField(
            model_name='anthemasset',
            name='anthemuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leet.AnthemUser'),
        ),
    ]
