# Generated by Django 3.0 on 2019-12-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0006_auto_20191231_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthemasset',
            name='anthem_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anthem_users', to='leet.AnthemUser'),
        ),
    ]
