# Generated by Django 3.0 on 2020-01-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0007_auto_20191231_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthemuser',
            options={'ordering': ['department']},
        ),
    ]
