# Generated by Django 3.0 on 2020-01-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0008_auto_20200102_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthemuser',
            options={'ordering': ['name']},
        ),
    ]
