# Generated by Django 3.0 on 2020-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0009_auto_20200102_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthemasset',
            name='asset_picture',
            field=models.ImageField(blank=True, null=True, upload_to='leet/equipment_pics'),
        ),
        migrations.AddField(
            model_name='anthemasset',
            name='manufacture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
