# Generated by Django 3.0 on 2020-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0010_auto_20200110_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthemuser',
            name='internal_ext',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
