# Generated by Django 3.0 on 2020-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0012_auto_20200111_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthemuser',
            name='manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
